modLoader="javafml"
loaderVersion="[${loader_version},)"
license="All rights reserved"
issueTrackerURL="https://github.com/MeinKraft/Crimson-XP/issues" #optional

[[mods]]
modId="crimsonxp"
version="${version}"
displayName="Crimson XP"
displayURL="https://www.curseforge.com/minecraft/mc-mods/crimson-xp-charm"
updateJSONURL = "https://github.com/MeinKraft/Crimson-XP/raw/main/update.json"
authors="§4Crimson_Fluff"
logoFile="logo.png" #optional
credits="\n§bTechnovision§r for his awesome modding YouTube series\n§bTurtyWurty§r for his awesome modding YouTube series" #optional
description=''' "Experienced in the art of attraction" '''

[[dependencies.crimsonxp]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    side="BOTH"
[[dependencies.crimsonxp]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    side="BOTH"
