modLoader="javafml"
loaderVersion="[${loader_version},)"
license="All rights reserved"
issueTrackerURL="https://github.com/MeinKraft/Crimson-Magnet/issues" #optional

[[mods]]
modId="crimsonxp"
version="${version}"
displayName="Crimson XP"
displayURL="http://crimsonfluff.com/"
updateJSONURL = "https://github.com/MeinKraft/Crimson-Magnet/raw/main/update.json"
authors="§4Crimson_Fluff"
logoFile="logo.png" #optional
credits="\n§bTechnovision§r for his awesome modding YouTube series\n§bTurtyWurty§r for his awesome modding YouTube series" #optional
description=''' "Attraction is in the eye of the beholder" '''

[[dependencies.crimsonxp]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    side="BOTH"
[[dependencies.crimsonxp]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    side="BOTH"
